#!/usr/bin/env escript
-export([main/1]).

-include_lib("kernel/include/file.hrl").

main(Something) when is_list(Something) ->
    [Command | Args] = Something,
    case Command of
	"new" ->
	    handle(Command, Args);
	"help" ->
	    handle(Command, Command);
	_ ->
	    case app_created() of
		true ->
		    handle(Command, Args);
		false ->
		    io:format("You must create an app before you can do anything else.~n\tusage: wherl new <name> <abbreviation>~n",[])
	    end
    end;	

main(_) ->
    io:format("usage: wherl generate <command> <argument>. try wherl help for a list of commands.~n",[]).	

%%%===================================================================
%%% API
%%%===================================================================
handle("new", Args) ->
    case (length(Args)) of
	1 ->
	    [App] = Args,
	    new_app(App, "");
	2 ->  
	    [App | Rest] = Args,
	    [Abbrev] = Rest,
	    new_app(App, Abbrev);
	_ ->
	    io:format("usage: wherl new <name> <abbreviation>~n \tname: name of the application~n \tabbreviation: since erlang is not namespaced, a short (1-4 character) prefix can be appended to each module to avoid name clashes.~n",[]) %
    end;

handle("generate", ["controller" | Rest]) ->
    case (length(Rest) == 1) of
	true ->
	    Name = string:strip(Rest),
	    io:format("generating controller ~s~n",[Name]);
	false ->	
	    io:format("usage: wherl generate controller <name>~n",[])
    end;

handle("generate", ["model" | Rest]) ->
    case (length(Rest) == 0) of
	true ->
	    io:format("usage: wherl generate model <name>~n",[]);
	false ->	
	    [Name | Fields] = Rest,
	    io:format("generating model ~s~n",[Name]),
	    model(Name, Fields)
    end;

handle("generate", ["scaffold" | Rest]) ->
    case (length(Rest) == 1) of
	true ->
	    Name = string:strip(Rest),
	    io:format("generating model and controller ~s~n",[Name]);
	false ->	
	    io:format("usage: wherl generate <command> <args>~n",[])
    end;

handle(_, _) ->
    io:format("usage: wherl <command> <args>~n \tcommands:~n \t\tnew - create a new application~n \t\tgenerate - make a new model or controller~n",[]).

%%%===================================================================
%%% Template generation
%%%===================================================================
new_app(App, Abbrev) ->
    {ok, ConfigFile} = create_file(lists:flatten(["config", "/", "wherl.config"])),
    io:format("creating new app ~s~n",[App]),
    file:write(ConfigFile, io_lib:fwrite("~p.\n",[{app, App}])),
    file:write(ConfigFile, io_lib:fwrite("~p.\n",[{abbrev, Abbrev}])),
    CurrentDirectory = filename:dirname(escript:script_name()),
    AppDir = lists:flatten([CurrentDirectory, "/", App]),
    file:make_dir(AppDir), 
    io:format("creating directory:  ~s~n",[AppDir]),
    rebar_create(App, AppDir),
    hrl(App),
    util(App),
    ok.

rebar_create(App, AppDir) ->
    os:cmd("cp rebar " ++ AppDir),
    Cmd = "cd " ++ AppDir ++ "; ./rebar create-app appid=" ++ App,
    %%io:format("~s~n", [Cmd]),
    os:cmd(Cmd).

hrl(App) ->
    FileName = lists:flatten([App, "/include/", App, ".hrl"]),
    {ok, HrlFile} = create_file(FileName),
    file:write(HrlFile, "").
    
model(Model, Fields) ->
    Properties = model_properties(Model, Fields),
    TemplateFileName = "model.tmp",
    Data = template(TemplateFileName, Properties),
    FileName = lists:flatten([app_name(), "/src/", Model, ".erl"]),
    {ok, ModelFile} = create_file(FileName),
    Result = file:write(ModelFile, Data),
    wh_record(Properties),
    store(Model, Properties),
    io:format("~p~n", [Result]).

wh_record(Properties) ->
    App = app_name(),
    TemplateFileName = "record.tmp",
    Data = template(TemplateFileName, Properties),
    HrlFileName = lists:flatten([App, "/include/", App, ".hrl"]),
    io:format("creating file:  ~s~n",[HrlFileName]),
    {ok, HrlFile} = file:open(HrlFileName, [write, append]),
    file:write(HrlFile, Data).

store(Model, Properties) ->
    TemplateFileName = "store.tmp",
    Data = template(TemplateFileName, Properties),
    FileName = lists:flatten([app_name(), "/src/", Model, "_store.erl"]),
    io:format("creating file:  ~s~n",[FileName]),
    {ok, File} = file:open(FileName, [write]),
    file:write(File, Data).

util(App) ->
    Properties = [{app, App}],
    TemplateFileName = "util.tmp",
    Data = template(TemplateFileName, Properties),
    FileName = lists:flatten([app_name(), "/src/", App, "_util.erl"]),
    io:format("creating file:  ~s~n",[FileName]),
    {ok, File} = file:open(FileName, [write]),
    file:write(File, Data).

%%%===================================================================
%%% Utility functions
%%%===================================================================


template(TemplateFileName, Properties) ->
    CurrentDirectory = filename:dirname(escript:script_name()),
    true = code:add_pathz(CurrentDirectory ++ "/include/sgte/ebin/"),
    FileName = lists:flatten([CurrentDirectory, "/templates/", TemplateFileName]),
    {ok, Compiled} = sgte:compile_file(FileName),
    sgte:render_bin(Compiled, Properties).

create_file(FileNameAndPath) ->
    Index = string:rchr(FileNameAndPath, $/),
    Path = string:substr(FileNameAndPath, 1, Index - 1),
    CurrentDirectory = filename:dirname(escript:script_name()),
    lists:foldl(fun(Directory, PathSoFar) -> 
			NewDir = lists:flatten([PathSoFar, "/", Directory]),
			file:make_dir(CurrentDirectory ++ NewDir), 
			%%io:format("creating directory:  ~s~n",[CurrentDirectory ++ NewDir]),
			NewDir
		end, "", string:tokens(Path, "/ ")),
    FullFileName = lists:flatten([CurrentDirectory, "/", FileNameAndPath]),
    {ok, File} = file:open(FullFileName, [write]),
    io:format("creating file:  ~s~n",[FullFileName]),
    {ok, File}.

app_name() ->
    CurrentDirectory = filename:dirname(escript:script_name()),
    Filename = CurrentDirectory ++ "/config/wherl.config",
    {ok, PropList} = file:consult(Filename),
    {app, AppName} = lists:keyfind(app, 1, PropList),
    AppName.

app_created() ->
    CurrentDirectory = filename:dirname(escript:script_name()),
    Filename = CurrentDirectory ++ "/config/wherl.config",
    {Result, _} = file:read_file_info(Filename),
    Result == ok.

rebar_compile() ->
    Cmd = "cd " ++ app_name() ++ "; ./rebar compile",
    io:format("~s~n", [Cmd]),
    os:cmd(Cmd).

model_properties(Model, Fields) ->
    FieldTitleList = string:sub_string(lists:flatten([ ", " ++ title(F) || F <- Fields ]), 3),
    FieldRecordList = string:sub_string(lists:flatten([ ", " ++ F ++ "=" ++ title(F) || F <- Fields ]), 3),
    FieldList = string:sub_string(lists:flatten([ ", " ++ F || F <- Fields ]), 3),
    [{model, Model}, 
     {'Model', title(Model)},
     {app, app_name()},
     {field_count, length(Fields)},
     {field_title_list, FieldTitleList},
     {field_list, FieldList},
     {field_record_list, FieldRecordList},
     {abbrev, ""}].

title([H|T]) -> 
    [string:to_upper(H)| T].
